version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: jobportal-postgres
    restart: always
    environment:
      POSTGRES_DB: jobportal
      POSTGRES_USER: ali
      POSTGRES_PASSWORD: alimurad05
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
